name: unleash_client
description: A Server Side Dart SDK for Unleash. Unleash is an open-source feature flag service.
version: 0.4.5
repository: https://github.com/supy-io/supy-flutter-packages

environment:
  sdk: ^3.0.6
dependencies:
  meta: ^1.3.0
  http: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  coverage: ^1.0.2
  test: ^1.16.0
  yaml: ^3.0.0
  lints: ^2.1.1
