name: cerbos_http_client
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/supy-io/supy-flutter-packages

environment:
  sdk: ^3.0.6

dependencies:
  dio: ^5.3.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.5
