name: cerbos_http_client
description: Simple HTTP client to interact with Cerbos.
version: 0.0.3
repository: https://github.com/supy-io/supy-flutter-packages

environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.3.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.5
