name: opentelemetry_dart
version: 0.0.2
description: A framework for collecting traces from applications.
homepage: https://github.com/Workiva/opentelemetry-dart
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  dio: ^5.0.0
  fixnum: ^1.0.1
  logging: ^1.1.0
  protobuf: ^2.1.0
  quiver: ^3.1.0
  collection: ^1.17.2

dev_dependencies:
  mockito: ^5.3.2
  test: ^1.21.4
  workiva_analysis_options: ^1.3.0
